[[CUDA_Tile]]
arch = "aarch64"
git-tree-sha1 = "5e05cb69bfc16a1e1ee966148d8e2ab672b0348d"
os = "macos"

    [[CUDA_Tile.download]]
    sha256 = "4a47a422955ec1214d39afd54cd7cf067276d983972ef09b1f9e1c52a182e09b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Tile_jll.jl/releases/download/CUDA_Tile-v13.1.6+0/CUDA_Tile.v13.1.6.aarch64-apple-darwin.tar.gz"
[[CUDA_Tile]]
arch = "aarch64"
git-tree-sha1 = "4c10f23463d118fb9b0ae917091664a429bbd48e"
libc = "glibc"
os = "linux"

    [[CUDA_Tile.download]]
    sha256 = "ed5c1c12193392e1be6311e519c26f6b7129b2e16354c001f27cbf5eedf095c3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Tile_jll.jl/releases/download/CUDA_Tile-v13.1.6+0/CUDA_Tile.v13.1.6.aarch64-linux-gnu.tar.gz"
[[CUDA_Tile]]
arch = "x86_64"
git-tree-sha1 = "89098de70a4a6bd54e06435c7382dd15db78203b"
libc = "glibc"
os = "linux"

    [[CUDA_Tile.download]]
    sha256 = "2da3de42bbcdd38c4cccdbc652323a88944d6fb20fa85e0422c11e80426f965b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Tile_jll.jl/releases/download/CUDA_Tile-v13.1.6+0/CUDA_Tile.v13.1.6.x86_64-linux-gnu.tar.gz"
[[CUDA_Tile]]
arch = "x86_64"
git-tree-sha1 = "4ab17440834c7cab9887f1f0663e2e61ef7932ed"
os = "windows"

    [[CUDA_Tile.download]]
    sha256 = "2dfbaeae35cbf9cb613944c6d2ed7f1c7d3ebf924eeae3c9a1125959330a096c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Tile_jll.jl/releases/download/CUDA_Tile-v13.1.6+0/CUDA_Tile.v13.1.6.x86_64-w64-mingw32.tar.gz"
