[[CUDA_Tile]]
arch = "aarch64"
git-tree-sha1 = "f0de4fe23e84516da95db172a7b314b0d8d73aea"
os = "macos"

    [[CUDA_Tile.download]]
    sha256 = "a0af0c809b504770778794ee902dbb2c31763e63dc852c4b69f3458ba7679bd1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Tile_jll.jl/releases/download/CUDA_Tile-v13.1.8+0/CUDA_Tile.v13.1.8.aarch64-apple-darwin.tar.gz"
[[CUDA_Tile]]
arch = "aarch64"
git-tree-sha1 = "2420c70abf75a40f689740d846ee394f7a5565fe"
libc = "glibc"
os = "linux"

    [[CUDA_Tile.download]]
    sha256 = "abe9d97ba98d1f5e2606d415ca4e8735bbde39a477187d55f02d875d135c2339"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Tile_jll.jl/releases/download/CUDA_Tile-v13.1.8+0/CUDA_Tile.v13.1.8.aarch64-linux-gnu.tar.gz"
[[CUDA_Tile]]
arch = "x86_64"
git-tree-sha1 = "1fa500d4b5ef800c3341a33afbe7100f24489d72"
libc = "glibc"
os = "linux"

    [[CUDA_Tile.download]]
    sha256 = "536c07b53c66f3ecfc105da3d7951ad7d106b864d46f11fc746052702399b037"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Tile_jll.jl/releases/download/CUDA_Tile-v13.1.8+0/CUDA_Tile.v13.1.8.x86_64-linux-gnu.tar.gz"
[[CUDA_Tile]]
arch = "x86_64"
git-tree-sha1 = "4b948ea33dbdd7b906a9ea278b5127b4ff45294e"
os = "windows"

    [[CUDA_Tile.download]]
    sha256 = "8db8eba1725010aee078e9fd20053ec9e56439a0cfa60e3a25f5695656275b5e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Tile_jll.jl/releases/download/CUDA_Tile-v13.1.8+0/CUDA_Tile.v13.1.8.x86_64-w64-mingw32.tar.gz"
