# Autogenerated wrapper script for CUDA_Tile_jll for aarch64-linux-gnu
export cuda_tile_opt, cuda_tile_tblgen, cuda_tile_translate

JLLWrappers.@generate_wrapper_header("CUDA_Tile")
JLLWrappers.@declare_executable_product(cuda_tile_opt)
JLLWrappers.@declare_executable_product(cuda_tile_tblgen)
JLLWrappers.@declare_executable_product(cuda_tile_translate)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        cuda_tile_opt,
        "bin/cuda-tile-opt",
    )

    JLLWrappers.@init_executable_product(
        cuda_tile_tblgen,
        "bin/cuda-tile-tblgen",
    )

    JLLWrappers.@init_executable_product(
        cuda_tile_translate,
        "bin/cuda-tile-translate",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
